name: Build
on: [push, pull_request]
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - name: checkout code
      uses: actions/checkout@v1
    - name: install Go
      uses: actions/setup-go@v1
      with:
       go-version: 1.13.x
    - name: set GOPATH
      # temporary fix
      # see https://github.com/actions/setup-go/issues/14
      run: |
        echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
        echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
      shell: bash
    - name: install Go pkg
      run: |
       go get golang.org/x/mobile/cmd/gomobile
       go get golang.org/x/mobile/cmd/gobind
       go get github.com/golang/dep/cmd/dep
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: build tun2socks
      run: |
       # go get github.com/trojan-gfw/igniter-go-libs/...
       mkdir -p $GOPATH/src/github.com/trojan-gfw && cd $_
       git clone https://github.com/trojan-gfw/igniter-go-libs
       cd $GOPATH/src/github.com/trojan-gfw/igniter-go-libs
       dep ensure -update
       gomobile init
       make android
       cp build/golibs.aar $(dirname $GITHUB_WORKSPACE)/clash.icecream/app/libs/tun2socks.aar
       
    - name: build with Gradle
      run: ./gradlew build --stacktrace
    - name: Run Unit tests
      run: ./gradlew testDebugUnitTest
